name: Deploy Employee Portal (Backend + Frontend)

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  deploy-backend:
    name: Deploy Backend (SAM)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup AWS SAM
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: SAM Validate
        working-directory: Backend
        run: sam validate
      # ----------------------------
      # Backend: SAM Build
      # ----------------------------
      - name: SAM Build
        working-directory: Backend
        run: |
          sam build

      # ----------------------------
      # Backend: SAM Deploy (uses samconfig.toml)
      # ----------------------------
      - name: SAM Deploy (dev)
        working-directory: Backend
        run: |
          sam deploy --config-env dev

  deploy-frontend:
    name: Deploy Frontend (S3)
    needs: deploy-backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ----------------------------
      # Frontend: Upload website to S3
      # ----------------------------
      - name: Deploy frontend to S3
        run: |
          aws s3 sync Website/ s3://containers-club-dev-webbucket-elh1uro4wffs \
            --delete \
            --exact-timestamps


      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E18YOLZYXQWBEI \
            --paths "/*"